### ISSUE TITLE
NetworkStatistics.framework: bundle format unrecognized, invalid, or unsuitable

### ISSUE THREAD

**Issue by rei-vilo** [doug-leith/appFirewall#2]
**Describe the bug**
NetworkStatistics.framework: bundle format unrecognized, invalid, or unsuitable

**To Reproduce**
1. Go to **Signing and Capabilities** 
2. Set **Team** to my `(Personal Team)` for the six targets
3. Launch **Build**

**Expected behavior**
Successful build.

**Screenshots**

```
CodeSign /Users/<USER>/Library/Developer/Xcode/DerivedData/appFirewall-cvhgybcnlsmtmxgaterxoudekzdb/Build/Products/Debug/appFirewall.app/Contents/Frameworks/NetworkStatistics.framework/Versions/A (in target 'appFirewall' from project 'appFirewall')
    cd /Users/<USER>/Downloads/appFirewall-2.0
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "Apple Development: <USER_EMAIL> (<USER_NUMBER>)"

    /usr/bin/codesign --force --sign 4E040945829F2DED155A48F92D821EE67E25516B -o runtime --timestamp=none --preserve-metadata=identifier,entitlements,flags /Users/<USER>/Library/Developer/Xcode/DerivedData/appFirewall-cvhgybcnlsmtmxgaterxoudekzdb/Build/Products/Debug/appFirewall.app/Contents/Frameworks/NetworkStatistics.framework/Versions/A

/Users/<USER>/Library/Developer/Xcode/DerivedData/appFirewall-cvhgybcnlsmtmxgaterxoudekzdb/Build/Products/Debug/appFirewall.app/Contents/Frameworks/NetworkStatistics.framework/Versions/A: bundle format unrecognized, invalid, or unsuitable
Command CodeSign failed with a nonzero exit code
```

**Desktop (please complete the following information):**
 - OS: macOS 10.15.3 (19D76)
 - Xcode 11.3.1 (11C504)

Thank you!

**Comment by doug-leith** [comment]
Thanks.  That networks stats framework was something I was playing with originally until I found a better way to link network connections and processes together.  Its not used at all in the app, although I left the code in place just in case I wanted to go back to using it.  I’ll strip out the unused code and post an update - will likely be next week before I have time for it though.  

Doug

**Comment by doug-leith** [comment]
Would you mind having a go at compiling the version I just pushed to github and letting me know if that fixes things for you.  Thanks.

**Comment by rei-vilo** [comment]
Sure! 

Compilation succeeds only after removing the old frameworks related to `NetworkStatistics`. Please see below.

<img width="544" alt="Capture 2020-03-03 à 13 34 37" src="https://user-images.githubusercontent.com/951776/75776510-6fa5e300-5d54-11ea-98aa-892e5ebc9aa6.png">

**Comment by doug-leith** [comment]
thanks,  missed those ones.  i’ve just pushed a change that deletes them.

**Comment by rei-vilo** [comment]
New release builds fine, thank you for your help!

I'm closing this thread as the problem is solved now.
