### ISSUE TITLE
Consent is editable, black text on black background in Consent window when night theme is active

### ISSUE THREAD

**Issue by sigseg5** [doug-leith/appFirewall#3]
**Describe the bug**
Text in consent window is editable, more then, there are black text on black background in this window when night theme is active

**Screenshots**
<img width="551" alt="image" src="https://user-images.githubusercontent.com/36568961/75696719-d8964800-5ccd-11ea-9a7a-c4b17dd86294.png">

**Desktop:**
 - OS: macOS Catalina 10.15.3 (19D76)
 - Firewall version: Stable Release (v2.0.3)

**Comment by doug-leith** [comment]
Thanks, I’ll get those fixed.

**Comment by doug-leith** [comment]
Try the release I just pushed (v2.0.4), consent form issues should be fixed in that.

**Comment by sigseg5** [comment]
> Try the release I just pushed (v2.0.4), consent form issues should be fixed in that.

Yep, now its working perfect, thx
