### ISSUE TITLE
Implement removing rules

### ISSUE THREAD

**Issue by AlexanderWillner** [doug-leith/appFirewall#4]
**Is your feature request related to a problem? Please describe.**
Implement removing rules

**Describe the solution you'd like**
Open appFirewall.app > Select an entry in one of the lists > Remove it

**Describe alternatives you've considered**
Any form of removing rules is fine.

**Additional context**
Other options related to information, blocking, whitelisting are available.

**Comment by doug-leith** [comment]
That feature is already there, just click on the button to the right of any rule on the blacklist or whitelist windows.  Or did you mean something different?

**Comment by AlexanderWillner** [comment]
yeah, right, good. Let say then, it's a User Experience issue ;) Suggestion: rename "Allow" to "Remove" in the Blick List view an add the item "Remove" to the right click menu.

**Comment by doug-leith** [comment]
in that case i prefer to leave it as is.

**Comment by doug-leith** [comment]
closed
