### ISSUE TITLE
Always shows update to Version 2.04 (1)

### ISSUE THREAD

**Issue by AlexanderWillner** [doug-leith/appFirewall#5]
**Describe the bug**
AppFirewall (Version 2.04 (1)) always shows the update to Version 2.04 (1).

**To Reproduce**
1. Open appFirewall.app
2. Click on Check for Updates

**Expected behavior**
Claiming everything is up to date.

**Screenshots**
-/-

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: macOS
 - Browser [e.g. chrome, safari]: n/a
 - Version [e.g. 22]: 10.14.6 (18G3020)

**Additional context**
-/-

**Comment by doug-leith** [comment]
should be fixed now (a silly typo).

**Comment by AlexanderWillner** [comment]
Thanks. Works for me.
